### ISSUE TITLE
What OS/architecture were the profiles built for?

### ISSUE THREAD

**Issue by mindstormer12** [SpotComms/FirejailProfileGenerator#6]
What OS/architecture were the profiles built for? Latest version of Arch Linux 64-bit? Would be nice to include this information in the README, since profiles are architecture/OS-dependent.

**Comment by SpotComms** [comment]
The profiles for the most part closely match upstream, so OS shouldn't matter. But as of right now this project is basically dead since https://github.com/netblue30/firejail/commit/fa10ab0e093a4224b16491273b0162b0e0a77a3a. I did however upstream a few of the profiles I created in https://github.com/netblue30/firejail/commit/69009709796704a6d67827758be8b382672cf8f2. If you are on Arch I'd just recommend running firejail-git from the AUR.
